# Generated by Django 5.0.1 on 2024-02-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(max_length=50)),
                ('dob', models.DateTimeField()),
                ('degree', models.CharField(max_length=100)),
                ('linkedIn', models.URLField()),
                ('git_hub', models.URLField()),
                ('image_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=100)),
                ('certificate_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('school_address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('tasks', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_items', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Image')),
                ('image_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.about')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.certificate')),
                ('education_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.education')),
                ('experience_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.experience')),
                ('skill_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.skill')),
            ],
        ),
    ]
